<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

//$config['useragent'] = 'CodeIgniter';
//$config['protocol'] = 'smtp';
////$config['mailpath'] = '/usr/sbin/sendmail';
//$config['smtp_host'] = 'ssl://smtp.gmail.com';
//$config['smtp_user'] = 'alfred.laggner@gmail.com';
//$config['smtp_pass'] = 'Ilm2dogs12$$$';
//$config['smtp_port'] = 465; 
//$config['smtp_timeout'] = 10;
//$config['wordwrap'] = TRUE;
//$config['wrapchars'] = 76;
//$config['mailtype'] = 'html';
//$config['charset'] = 'utf-8';
//$config['validate'] = FALSE;
//$config['priority'] = 3;
//$config['crlf'] = "\r\n";
//$config['newline'] = "\r\n";
//$config['bcc_batch_mode'] = FALSE;
//$config['bcc_batch_size'] = 200;

$config['protocol'] = 'sendmail';
$config['mailpath'] = '/usr/sbin/sendmail';
$config['charset'] = 'iso-8859-1';
$config['wordwrap'] = TRUE;
$config['wrapchars'] = 76;
$config['mailtype'] = 'html';
$config['charset'] = 'utf-8';
$config['validate'] = FALSE;
$config['priority'] = 3;
$config['crlf'] = "\r\n";
$config['newline'] = "\r\n";
$config['bcc_batch_mode'] = FALSE;
$config['bcc_batch_size'] = 200;
